name: Create Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: python -m pip install -U "jupyterlab>=4.0.0,<5"

      - name: Build the extension
        run: |
          set -eux
          python -m pip install .[test]

          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "idle-redirector.*OK"
          python -m jupyterlab.browser_check

      - name: Package the extension
        run: |
          set -eux

          pip install build
          python -m build
          pip uninstall -y "idle_redirector" jupyterlab

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "dist/idle_redirector*"
          body: Idle Redirector release - ${{ github.ref }}
